name: Run Bun Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch: # Enables manual trigger

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Run Tests
              run: bun test
